name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build
        env:
          VITE_USE_ONLINE: ${{ secrets.USE_ONLINE }}
          VITE_DEVICES_URL: ${{ secrets.DEVICES_URL }}
          VITE_BLOGS_URL: ${{ secrets.BLOGS_URL}}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
